defaultSize: 5
logging:
  level: INFO
  loggers:
    couture: DEBUG
apiUsername : login
apiPassword : logic
database:
  driverClass: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/brands?autoReconnect=true&useSSL=false
  user: root
  password: 12345678
  maxWaitForConnection: 1s
  validationQuery: "SELECT 1"
  validationQueryTimeout: 3s
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false
  evictionInterval: 10s
  minIdleTime: 1 minute
  checkConnectionOnBorrow: true

